<?php

namespace AppBundle\Repository;

/**
 * ComfortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComfortRepository extends \Doctrine\ORM\EntityRepository
{
}
