<?php

namespace AppBundle\Repository;

/**
 * DealerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealerRepository extends \Doctrine\ORM\EntityRepository
{
}
