<?php

namespace AppBundle\Repository;

/**
 * EnergyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnergyRepository extends \Doctrine\ORM\EntityRepository
{
}
